trigger:
- main

# Build on multiple OS
# strategy:
#   matrix:
#     linux:
#       operatingSystem: 'ubuntu-latest'
#     mac:
#       operatingSystem: 'macos-latest'

pool:
  # vmImage: $(operatingSystem)
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - bash: echo "Do the build"
    
- stage: DevDeploy
  jobs: 
  # deployment is also a job with additional features
  - deployment: DevDeployJob
    # Assign env to this job
    environment: Dev
    # Specify steps
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to Dev
- stage: QADeploy
  jobs: 
  - deployment: QADeployJob
    environment: QA
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to QA